### PR TITLE
Refactored MainActivity and AppDataUsageFragment to Kotlin, introduce…

### PR DESCRIPTION
**Pull request by yatiksihag01**
- Migrated `MainActivity.java` and `AppDataUsageFragment.java` to Kotlin.
- Implemented single responsibility principle and survive configuration changes by moving backend logic to `DataUsageViewModel.kt` and `UsageDataHelperImpl.kt`.
- Created a new `UsageDataAdapter.kt` using `AsyncListDiffer` and moved click listeners into `AppDataUsageFragment.kt`, which will improve efficiency.
- Replaced `AsyncTask` operations with Kotlin coroutines, significantly decreasing `AppDataUsageFragment.kt` loading time.
- Added a debug suffix for the debug package to allow the installation of both release and debug versions on the device simultaneously.
- Minor bug fixes.

### CODE REVIEW

**Comment by soshial** [comment]
It used AsyncTask?? Sweet mother of god!
Thank you @yatiksihag01

**Comment by yatiksihag01** [comment]
@soshial 97% of the code is still in Java, so the use of AsyncTask is expected. The app has a great UI and good features, but the project needs to be migrated to Kotlin following proper architecture guidelines to reduce complexity and improve performance.

**Comment by itsdrnoob** [comment]
@yatiksihag01 So I've been testing out the PR, and here's a few things the I noticed.

- The data usage count of "System Apps" in the "AppDataUsageFragment" seems to be inaccurate.
- "System Apps" list is refreshed again when opened for the first time and the value remains unchanged even when the main "App usage" is refreshed.
- Upon changing the session, data usage values seem to not update for certain items, which could be an issue with the adapter as the values change once the views are recycled.
- On refreshing the list, the existing list kind of flashes once before the loading shimmer is shown.
- The usage filter can be changed during a refresh, which could lead to a potential `NullPointerException`
- The loading shimmer is shown every time on switching fragments, which is not ideal when the list is not refreshing.

These were my initial impressions before any in-depth testing, so feel free to update me. Also, the build was compared against the release/2.3.2 build.

**Comment by yatiksihag01** [comment]
@itsdrnoob Thanks for your feedback. Sorry I'm a bit busy for few days, but I'll review and address the issues as soon as possible.

**Comment by itsdrnoob** [comment]
@yatiksihag01 No worries. I'll just keep the PR open for the time being. 
I've updated the base branch to dev/2.4.0. Please make sure to fetch the latest changes to avoid any merge conflicts.

**Comment by yatiksihag01** [comment]
Thanks. Don't worry I'll fetch the latest changes to prevent any potential merge conflicts.

**Comment by yatiksihag01** [comment]
Hi @itsdrnoob, I'm closing this PR and opening a new one as I've rebased this branch onto dev/2.4.0

**Pull request closed without merging**
